export const products = [
  {
    id: 1,
    name: "Natural Powder",
    image_primary: "/images/products/product_1_primary.png",
    image_secondary: "/images/products/product_1_secondary.png",
    price: 15.0,
    priceFrom: 10.0,
    priceTo: 20.0,
    category: ["Blender", "Body Spray"],
    colors: ["Black", "White", "Red", "Pink", "Beige", "Clear", "Multi"],
    rating: 4.5,
  },
  {
    id: 2,
    name: "Matte Foundation",
    image_primary: "/images/products/product_2_primary.png",
    image_secondary: "/images/products/product_2_secondary.png",
    price: 12.0,
    priceFrom: 10.0,
    priceTo: 20.0,
    category: ["Body Spray", "Concealer"],
    colors: ["Black", "White", "Red", "Pink", "Beige", "Clear", "Multi"],
    rating: 4.5,
  },
  {
    id: 3,
    name: "Shimmer Blush",
    image_primary: "/images/products/product_3_primary.png",
    image_secondary: "/images/products/product_3_secondary.png",
    price: 10.0,
    priceFrom: 10.0,
    priceTo: 20.0,
    category: ["Blender", "Concealer"],
    colors: ["Black", "White", "Red", "Pink", "Beige", "Clear", "Multi"],
    rating: 4.5,
  },
  {
    id: 4,
    name: "Matte Foundation",
    image_primary: "/images/products/product_2_primary.png",
    image_secondary: "/images/products/product_2_secondary.png",
    price: 12.0,
    priceFrom: 10.0,
    priceTo: 20.0,
    category: ["Body Spray", "Concealer"],
    colors: ["Black", "White", "Red", "Pink", "Beige", "Clear", "Multi"],
    rating: 4.5,
  },
  {
    id: 5,
    name: "Natural Powder",
    image_primary: "/images/products/product_1_primary.png",
    image_secondary: "/images/products/product_1_secondary.png",
    price: 8.0,
    priceFrom: 10.0,
    priceTo: 20.0,
    category: ["Blender", "Body Spray"],
    colors: ["Black", "White", "Red", "Pink", "Beige", "Clear", "Multi"],
    rating: 4.5,
  },
];
